[global]
daemonize = no

[www]
user = 1000
group = 1000
listen = /tmp/php-fpm.sock

listen.mode = 0666
listen.owner = 1000
listen.group = 1000

ping.path = /ping-fpm

pm.status_path = /phpfpmstatus

pm.max_children = 250
pm.max_requests = 10
pm.min_spare_servers = 2
pm.max_spare_servers = 10
