FROM dunglas/frankenphp:1-php8.4

ARG APP_BUILD_VERSION=0.0.0.0
ENV APP_BUILD_VERSION=${APP_BUILD_VERSION}

WORKDIR /app

ENV APP_ENV=prod
ENV APP_DEBUG=0

# Install system packages
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libicu-dev \
    libzip-dev \
    libxml2-dev \
    nano \
    dnsutils \
    curl \
    wget \
    iputils-ping \
    net-tools \
    iproute2 \
    traceroute \
    tcpdump \
    mtr \
    netcat-openbsd \
    procps \
    && rm -rf /var/lib/apt/lists/*

RUN install-php-extensions \
    pdo_mysql \
    intl \
    zip \
    opcache \
    gd \
    redis \
    dom \
    xml

RUN git config --global --add safe.directory /app

RUN ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && echo "Europe/Berlin" > /etc/timezone

RUN apt-get update && apt-get install -y tzdata
ENV TZ=Europe/Berlin

COPY frontend /app/frontend
COPY shared-domain /app/shared-domain
RUN chown -R www-data:www-data /app

WORKDIR /app/frontend

COPY frontend/docker/php/custom.ini /usr/local/etc/php/conf.d/custom.ini
COPY frontend/docker/Caddyfile /etc/caddy/Caddyfile
CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
