services:
  ## CONTAINERS
  frontend:
    image: ghcr.io/vestalisde/vestalis_photo-frontend:latest
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      SERVER_NAME: ":8080"
      DOCKER_LOG_LEVEL: "INFO"
      LOG_ERROR_PATH: "php://stderr"
      APP_DEFAULT_TIMEZONE: "${APP_DEFAULT_TIMEZONE:-Europe/Berlin}"
    volumes:
      - ./frontend/public:/app/frontend/public
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.vestalis_photo-frontend.rule=Host(`photo.vestalis.de`)
      - traefik.http.routers.vestalis_photo-frontend.entrypoints=websecure
      - traefik.http.routers.vestalis_photo-frontend.tls.certresolver=lehttp
      - traefik.http.services.vestalis_photo-frontend.loadbalancer.server.port=80

networks:
  proxy:
    name: "proxy"
    external: true
