upload_max_filesize = 200M
post_max_size = 200M
client_max_body_size = 200M
date.timezone = Europe/Berlin
display_errors = 0
display_startup_errors = 0
max_input_vars = 2000
session.cookie_httponly = 1
session.use_strict_mode = 1
session.cookie_secure = 1
session.gc_maxlifetime = 14400
variables_order=EGPCS
apc.enable_cli = 1
apc.shm_size = 512M
apc.stat = 0
session.auto_start = Off
short_open_tag = Off
memory_limit = ${MEMORY_LIMIT}
max_execution_time = ${MAX_EXECUTION_TIME}

# https://symfony.com/doc/current/performance.html
opcache.interned_strings_buffer = 128

; The maximum number of keys (scripts) in the OPcache hash table.
; Only numbers between 200 and 1000000 are allowed.
opcache.max_accelerated_files = 1000000

; The OPcache shared memory storage size.
opcache.memory_consumption = 512
opcache.preload_user = bootstrap_user
opcache.preload = /app/config/preload.php

## Blackfire recommendations
opcache.enable_file_override = true
zend.detect_unicode = false
opcache.validate_timestamps = true

; maximum memory allocated to store the results
realpath_cache_size = 4096K

; save the results for 10 minutes (600 seconds)
realpath_cache_ttl = 600

expose_php = Off
